function readEnv(key: string): string | undefined {
  const value = process.env[key];
  if (!value || value.trim() === "") return undefined;
  return value;
}

export const env = {
  DATABASE_URL: readEnv("DATABASE_URL"),
  OPENAI_API_KEY: readEnv("OPENAI_API_KEY"),
  STRIPE_SECRET_KEY: readEnv("STRIPE_SECRET_KEY"),
  STRIPE_WEBHOOK_SECRET: readEnv("STRIPE_WEBHOOK_SECRET"),
  RESEND_API_KEY: readEnv("RESEND_API_KEY"),
  NEXT_PUBLIC_APP_URL: readEnv("NEXT_PUBLIC_APP_URL") ?? "http://localhost:3000",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: readEnv("NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"),
  STRIPE_PRICE_SEEKER_MONTHLY: readEnv("STRIPE_PRICE_SEEKER_MONTHLY"),
  STRIPE_PRICE_INITIATE_MONTHLY: readEnv("STRIPE_PRICE_INITIATE_MONTHLY"),
  CREDIT_PURCHASES_ENABLED: readEnv("CREDIT_PURCHASES_ENABLED"),
  STRIPE_PRICE_AI_CREDIT_PACK: readEnv("STRIPE_PRICE_AI_CREDIT_PACK"),
  ADMIN_EMAILS: readEnv("ADMIN_EMAILS"),
  INTERNAL_AGENT_API_KEY: readEnv("INTERNAL_AGENT_API_KEY"),
  EMAIL_FROM: readEnv("EMAIL_FROM"),
  CRON_SECRET: readEnv("CRON_SECRET"),
  EMAIL_SENDING_ENABLED: readEnv("EMAIL_SENDING_ENABLED"), // set to "true" to enable live sending
  PRACTICE_GENERATION_MODE: readEnv("PRACTICE_GENERATION_MODE"), // "openai" to use AI generation; default is placeholder
  SOCIAL_LISTENING_ENABLED: readEnv("SOCIAL_LISTENING_ENABLED"),
  SOCIAL_PUBLISHING_ENABLED: readEnv("SOCIAL_PUBLISHING_ENABLED"),
  MASTODON_BASE_URL: readEnv("MASTODON_BASE_URL"),
  MASTODON_ACCESS_TOKEN: readEnv("MASTODON_ACCESS_TOKEN"),
  X_BEARER_TOKEN: readEnv("X_BEARER_TOKEN"),
  X_USER_ACCESS_TOKEN: readEnv("X_USER_ACCESS_TOKEN"),
  X_API_KEY: readEnv("X_API_KEY"),
  X_API_SECRET: readEnv("X_API_SECRET"),
  X_ACCESS_TOKEN: readEnv("X_ACCESS_TOKEN"),
  X_ACCESS_TOKEN_SECRET: readEnv("X_ACCESS_TOKEN_SECRET"),
  X_PUBLISHING_ENABLED: readEnv("X_PUBLISHING_ENABLED"),
  LINKEDIN_ACCESS_TOKEN: readEnv("LINKEDIN_ACCESS_TOKEN"),
  LINKEDIN_AUTHOR_URN: readEnv("LINKEDIN_AUTHOR_URN"),
  LINKEDIN_VERSION: readEnv("LINKEDIN_VERSION"),
  LINKEDIN_PUBLISHING_ENABLED: readEnv("LINKEDIN_PUBLISHING_ENABLED"),
  META_GRAPH_VERSION: readEnv("META_GRAPH_VERSION"),
  META_PAGE_ID: readEnv("META_PAGE_ID"),
  META_PAGE_ACCESS_TOKEN: readEnv("META_PAGE_ACCESS_TOKEN"),
  INSTAGRAM_USER_ID: readEnv("INSTAGRAM_USER_ID"),
  FACEBOOK_PUBLISHING_ENABLED: readEnv("FACEBOOK_PUBLISHING_ENABLED"),
  INSTAGRAM_PUBLISHING_ENABLED: readEnv("INSTAGRAM_PUBLISHING_ENABLED"),
  THREADS_APP_SECRET: readEnv("THREADS_APP_SECRET"),
  THREADS_ACCESS_TOKEN: readEnv("THREADS_ACCESS_TOKEN"),
  THREADS_PUBLISHING_ENABLED: readEnv("THREADS_PUBLISHING_ENABLED"),
  PINTEREST_APP_ID: readEnv("PINTEREST_APP_ID"),
  PINTEREST_APP_SECRET: readEnv("PINTEREST_APP_SECRET"),
  PINTEREST_ACCESS_TOKEN: readEnv("PINTEREST_ACCESS_TOKEN"),
  PINTEREST_REFRESH_TOKEN: readEnv("PINTEREST_REFRESH_TOKEN"),
  PINTEREST_BOARD_ID: readEnv("PINTEREST_BOARD_ID"),
  PINTEREST_PUBLISHING_ENABLED: readEnv("PINTEREST_PUBLISHING_ENABLED"),
  BLUESKY_SERVICE_URL: readEnv("BLUESKY_SERVICE_URL"),
  BLUESKY_IDENTIFIER: readEnv("BLUESKY_IDENTIFIER"),
  BLUESKY_APP_PASSWORD: readEnv("BLUESKY_APP_PASSWORD"),
  PRIVATE_DATA_ENCRYPTION_KEY: readEnv("PRIVATE_DATA_ENCRYPTION_KEY"),
};

export function requireEnv(key: keyof typeof env): string {
  const value = env[key];
  if (!value) {
    throw new Error(`Missing required environment variable: ${key}`);
  }
  return value;
}
