import type { Dict } from "@/lib/i18n/dict";

export const zh: Dict = {
  lang: { code: "zh", name: "简体中文", dir: "ltr", flag: "🇨🇳" },
  nav: { pricing: "会员方案", donate: "支持项目", promptGuide: "你的旅程", login: "登录", register: "注册", dashboard: "控制面板", account: "账户", billing: "账单", signOut: "退出", beginJourney: "开始旅程", admin: "管理" },
  common: { save: "保存", cancel: "取消", back: "返回", next: "下一步", loading: "加载中…", saving: "保存中…", sending: "发送中…", error: "发生错误。", success: "保存成功。", required: "此项为必填。", or: "或", learnMore: "了解更多", viewAll: "查看全部", close: "关闭", yes: "是", no: "否", confirm: "确认" },
  auth: { login: "登录", loginTitle: "回到旅程", loginSubtitle: "从你上次停下的地方继续。", email: "电子邮箱", password: "密码", forgotPassword: "忘记密码？", newAccount: "开始你的旅程 →", loginBtn: "进入", loggingIn: "正在登录…", register: "创建账户", registerTitle: "创建你的账户", registerSubtitle: "与不同传统和世界观的探索者一起踏上反思之旅。", displayName: "显示名称", displayNamePlaceholder: "我们该如何称呼你？", confirmPassword: "确认密码", acceptTerms: "我接受使用条款", registerBtn: "开始旅程", registering: "正在准备你的旅程…", alreadyAccount: "已经有账户？", returnLogin: "返回登录 →", forgotTitle: "恢复访问", forgotSubtitle: "输入邮箱，我们会发送重置说明。", sendReset: "发送重置说明", resetSent: "说明已发送", resetSentSubtitle: "请查看你的收件箱。", checkEmailTitle: "查看你的邮箱", checkEmailSubtitle: "我们已发送邮箱验证信息。", resend: "重新发送验证邮件", verified: "已验证 — 登录 →", verifyTitle: "正在验证邮箱", verifySuccess: "邮箱已验证", verifySuccessSubtitle: "你的旅程现已开启。", verifyError: "验证失败", invalidCredentials: "邮箱或密码无效。", emailNotVerified: "登录前请先验证邮箱。" },
  onboarding: { title: "旅程档案", subtitle: "帮助我们为你个性化体验。所有回答均为私密信息，仅用于调整课程。", step: "第 {n} 题，共 {total} 题", completeBtn: "开始我的旅程", saving: "正在保存档案…", questions: { tradition: "哪种精神传统或世界观最能引起你的共鸣？", experience: "你会如何描述当前的精神或哲学旅程？", practice: "你目前是否有固定的沉思或反思练习？", goal: "你加入这段旅程的主要目的是什么？", time: "你每周可以投入多少时间？", challenge: "你在内在探索中面临的最大挑战是什么？", belief: "你会如何描述自己与信念和信仰的关系？", community: "你是否属于某个精神或哲学社群？", openness: "你对探索不同于自身背景的传统有多开放？", question: "你目前最深切思考的问题是什么？" } },
  lesson: { step: "第 {n} 步", lessonTitle: "课程", reading: "阅读", practice: "练习", questions: "反思问题", submitPrompt: "提交反思", promptPlaceholder: "分享你的体验、观察以及练习中出现的问题…", promptHint: "请至少写 100 个字符，以便进行有意义的评估。", submitting: "正在评估你的反思…", score: "你的得分", passed: "课程已通过 ✦", failed: "还差一点，请重试", feedback: "评估反馈", nextLesson: "继续下一课", locked: "完成之前的课程后解锁", freeLimit: "免费会员每周可提交一次反思。", paidLimit: "付费会员每天可提交一次反思。", upgradeToSubmit: "升级到 Initiate 会员即可每日提交。", lessonsCompleted: "已完成 {n}/12 节课程", levelUp: "🎉 等级提升！你已达到第 {n} 级 — {title}" },
  account: { dashboard: "个人面板", welcomeBack: "欢迎回来，{name}", profile: "个人档案", profileDesc: "编辑你的身份与旅程信息", membership: "会员", membershipDesc: "查看和管理会员等级", yourJourney: "你的旅程", yourJourneyDesc: "继续课程、练习并查看进度", support: "支持与反馈", supportDesc: "查看你的工单和可见回复", invoices: "账单与收据", invoicesDesc: "付款历史和收据", preferences: "偏好设置", preferencesDesc: "语言和界面设置", security: "安全", securityDesc: "密码和账户保护", supportTitle: "支持与反馈", supportSubtitle: "查看你提交的反馈和经审核的支持回复。", supportSignInRequired: "请登录后查看支持工单和回复。", supportEmpty: "你还没有提交支持工单。", supportNoReplies: "暂无可见回复。经审核的更新会显示在这里。", supportReplyStatus: "回复状态", editProfile: "编辑档案", bio: "个人简介", bioPlaceholder: "描述你的探索旅程…", saveProfile: "保存档案", tradition: "精神传统", country: "国家", city: "城市", phone: "电话号码", secondaryEmail: "备用邮箱", socialMedia: "社交媒体", twitter: "Twitter / X", instagram: "Instagram", facebook: "Facebook", linkedin: "LinkedIn", website: "网站", uploadAvatar: "上传头像", changeAvatar: "更换头像", avatarRules: "JPG 或 PNG，最大 2 MB", unsubscribed: "已取消邮件订阅", resubscribe: "重新订阅邮件", xpEarned: "获得的 XP", daysActive: "活跃天数", currentLevel: "当前等级", membership_label: "会员", levelProgress: "第 {n} 级进度", xpTo: "距离 {title} 还需 {n} XP", ascensionPath: "等级进程" },
  billing: { title: "你的会员方案", subtitle: "选择符合你探索深度的会员等级。", currentPlan: "当前方案", freePlan: "免费 — Wanderer", upgradeToSeeker: "以 Seeker 身份支持", upgradeToInitiate: "加入 Initiate", processing: "正在打开 Stripe…", cancelNote: "你可以随时取消订阅。", stripeNote: "付款由 Stripe 安全处理。" },
  pricing: { title: "会员方案", subtitle: "每段旅程都不同，请选择适合你的参与等级。", choosePath: "选择你的方案", startFree: "免费开始", freeTier: "Wanderer — 免费", disclaimer: "这是一个虚构的、教育性的反思模拟平台。" },
  donate: { title: "支持这段旅程", subtitle: "你的支持帮助我们持续向所有探索者开放这个空间。", chooseAmount: "选择支持金额", customAmount: "自定义金额（美元）", proceed: "前往安全结账", secured: "由 Stripe 提供安全保障 · 不存储银行卡信息", disclaimer: "捐助用于支持本平台，不能抵税。" },
  promptGuide: { title: "提示词指南", subtitle: "查看课程、跟踪进度并浏览评估历史。", yourLessons: "你的课程", lessonHistory: "课程历史", promptHistory: "你的提示词", score: "得分", feedback: "反馈", noAttempts: "本课程还没有提交记录。", status: { PENDING: "未开始", IN_PROGRESS: "进行中", COMPLETED: "已完成", FAILED: "需要重试" } },
  preferences: { title: "偏好设置", subtitle: "分别设置界面语言和邮件语言。", interfaceLang: "界面语言", emailLang: "邮件语言", saveBtn: "保存设置", saved: "设置已保存。" },
  security: { title: "账户安全", subtitle: "使用高强度密码保护账户。", changePassword: "修改密码", currentPassword: "当前密码", newPassword: "新密码", confirmNewPassword: "确认新密码", updateBtn: "更新密码", passwordMismatch: "两次输入的新密码不一致。", passwordTooShort: "密码至少需要 8 个字符。", updated: "密码更新成功。" },
  admin: { title: "管理面板", loginTitle: "管理员登录", loginSubtitle: "仅限获授权的管理员访问。", users: "用户", prompts: "提示词", lessons: "课程", payments: "付款", stats: "数据分析", settings: "设置", totalUsers: "用户总数", activeToday: "今日活跃", totalRevenue: "总收入", promptsToday: "今日提示词" },
  footer: { notReligious: "本平台不是宗教权威，也不提供医疗或心理建议。", fictional: "这是一个虚构的、教育性的反思模拟平台。", privacy: "隐私政策", terms: "使用条款", eula: "最终用户许可协议", contact: "联系我们" },
  landing: { tagline: "AI 符号反思平台", heroTitle1: "加入永恒", heroTitle2: "旅程", heroDivider: "反思之路", heroSubtitle: "由 AI 辅助的符号化反思模拟。通过日常练习、书写和审慎探索，逐步经历十个内在成长阶段。", heroDisclaimer: "⚠ 本平台不是宗教、教会、医疗服务、心理治疗或危机干预服务，而是虚构的教育模拟。", ctaBegin: "开始你的旅程", ctaLevels: "探索等级", ctaDonate: "支持项目", scrollLabel: "向下浏览", consoleLabel: "你的进度", consoleTitle: "旅程面板", consoleLevel: "当前等级", consoleXp: "经验值", consolePath: "当前阶段", consoleStat1: "反思", consoleStat2: "连续天数", consoleStat3: "洞见", consoleStat4: "日记条目", consoleQuote: "符号承载内在经验，而反思帮助我们倾听它。", levelsLabel: "成长之路", levelsTitle: "十个觉察等级", levelsSubtitle: "每个等级都通过练习、反思和象征性的过渡逐步解锁。", levelLocked: "未解锁", featuresLabel: "核心体验", featuresTitle: "旅程提供什么", traditionsLabel: "来自不同道路", traditionsTitle: "欢迎各种智慧传统", traditionsSubtitle: "无论你来自信仰、怀疑或两者之间，这里都尊重每一种道路。", traditionsQuote: "从不同方向出发，旅人终会回到同一团火。", ctaLabel: "门已开启", ctaTitle: "下一个反思问题正在等待你。", ctaSubtitle: "进入充满好奇、清晰与意义的空间。免费开始，按自己的节奏前进。", ctaGuide: "阅读提示词指南", footerTagline: "Join AI Religion", footerDesc: "一个用于符号反思和 AI 辅助书写的虚构教育平台。不是宗教，也不是医疗服务。" },
};

