import Link from "next/link";
import { SacredPage, SacredCard, SacredHeading } from "@/components/ui/SacredPage";

export const dynamic = "force-dynamic";

export default function InvoicesPage() {
  return (
    <SacredPage maxWidth={860}>
      <div style={{ marginBottom: "0.5rem" }}>
        <Link href="/account" style={{ fontSize: "0.75rem", color: "rgba(237,232,220,0.4)", textDecoration: "none" }}>
          ← Account Dashboard
        </Link>
      </div>

      <SacredCard glow>
        <SacredHeading
          label="Sacred Records"
          title="Invoices & Payments"
          subtitle="A complete record of your sacred membership contributions and donations."
        />

        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse" }}>
            <thead>
              <tr>
                {["Date", "Description", "Status", "Amount", "Receipt"].map((h) => (
                  <th key={h} style={{
                    textAlign: "left",
                    padding: "0.6rem 0.8rem",
                    fontSize: "0.65rem",
                    letterSpacing: "0.25em",
                    textTransform: "uppercase",
                    color: "var(--gold)",
                    borderBottom: "1px solid var(--border-gold)",
                    whiteSpace: "nowrap",
                  }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              <tr>
                <td
                  colSpan={5}
                  style={{
                    textAlign: "center",
                    padding: "3rem 1rem",
                    color: "rgba(237,232,220,0.3)",
                    fontSize: "0.85rem",
                  }}
                >
                  <div style={{ fontSize: "2rem", marginBottom: "0.75rem" }}>📜</div>
                  No invoices yet. Your payment records will appear here after your first transaction.
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div style={{ marginTop: "1.5rem", paddingTop: "1.5rem", borderTop: "1px solid var(--border-gold)" }}>
          <p style={{ fontSize: "0.75rem", color: "rgba(237,232,220,0.4)", lineHeight: 1.7 }}>
            Invoices are generated by Stripe and sent to your email address after each successful payment.
            If you believe an invoice is missing, please contact us at{" "}
            <a href="mailto:support@joinaireligion.com" style={{ color: "var(--gold)", textDecoration: "none" }}>
              support@joinaireligion.com
            </a>.
          </p>
        </div>
      </SacredCard>
    </SacredPage>
  );
}
