"use client";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function RegisterPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [acceptedTerms, setAcceptedTerms] = useState(false); const [emailOptIn, setEmailOptIn] = useState(false); const [beliefBackground, setBeliefBackground] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const router = useRouter();
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(""); setLoading(true); try { const res = await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,acceptedTerms,emailOptIn,beliefBackground})}); const data=await res.json(); if(!res.ok){setError(data.error||'Registration failed');return;} router.push(data.next || `/check-email?email=${encodeURIComponent(email)}`);} catch {setError('Network error. Please try again.');} finally{setLoading(false);} };
  return <main className="min-h-screen p-6"><div className="mx-auto max-w-md rounded-xl border border-slate-700 bg-slate-900 p-6"><h1 className="text-3xl">Create account</h1><form onSubmit={submit} className="mt-4 space-y-3"><input className="w-full rounded bg-slate-950 p-2" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} /><input type="password" className="w-full rounded bg-slate-950 p-2" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} /><textarea className="w-full rounded bg-slate-950 p-2" placeholder="İnanç/kültürel arka planın (opsiyonel)" value={beliefBackground} onChange={e=>setBeliefBackground(e.target.value)} />
          <label className="block text-sm"><input type="checkbox" checked={acceptedTerms} onChange={e=>setAcceptedTerms(e.target.checked)} className="mr-2"/>I accept the <Link href="/legal/eula" className="underline">terms</Link>.</label><label className="block text-sm"><input type="checkbox" checked={emailOptIn} onChange={e=>setEmailOptIn(e.target.checked)} className="mr-2"/>Receive emails/notifications (<Link href="/legal/email-consent" className="underline">policy</Link>).</label>{error && <p className="text-red-300">{error}</p>}<button disabled={loading} className="w-full rounded bg-violet-600 p-2">{loading?'Creating account...':'Create account'}</button></form><p className="mt-3 text-sm">Have an account? <Link className="underline" href="/login">Login</Link></p></div></main>;
}
